### ISSUE TITLE
Site seems slow to load

### ISSUE THREAD

**Issue by amirmc** [mirage/mirage-www#351] opened 2015-06-29 17:10 UTC
The new site seems slow to load.  It occasionally appears as though the page has hung and reloading is necessary.

Are there any outstanding issues that this might be related to?

**Comment by hannesm** [comment] 2015-06-29 17:16
this occassionally happened to the http site as well, btw... also, looking at the stats not sure if all the memory leaks are gone or not..

**Comment by amirmc** [comment] 2015-06-29 17:18
Yup, but I used to notice that less often in recent times (I felt that I rarely had to wait for the page to load).  I thought we'd fixed the recent networking issues. @samoht any thoughts?

**Comment by samoht** [comment] 2015-06-29 18:20
@magnusm found that we got a lot of retransmissions (there is an issue in mirage-tcpip bug tracker)

**Comment by amirmc** [comment] 2015-06-29 18:36
These seem to be the issues Thomas is referring to (just so they're linked):

- https://github.com/mirage/mirage-tcpip/issues/140
- https://github.com/mirage/mirage-tcpip/issues/157

**Comment by djs55** [comment] 2015-06-29 19:37
Separately from TCP, I notice the is large variation in ping time:

https://github.com/mirage/mirage-www/issues/352

The console is also fairly busy -- the kernel might be blocking performing
these writes. Here's a sample (lots fly past if you connect to it):

200 GET /css/font-awesome.css
200 GET /js/vendor/custom.modernizr.js
200 GET /js/vendor/jquery.min.js
200 GET /js/foundation/foundation.min.js
200 GET /js/foundation/foundation.topbar.js
200 GET /js/vendor/highlight.pack.js
200 GET /graphics/mirage-logo-small.png
200 GET /graphics/pinata_access.png
200 GET /graphics/cloud-bg.png
Tcp.Segment: TCP retransmission on timer seq = 452895699
conn 6669 closed
Tcp.Segment: TCP retransmission on timer seq = 452891750
conn 6513 closed
conn 6515 closed
conn 6516 closed
conn 6512 closed
conn 6514 closed
[104.192.218.186:55307] TLS eof
conn 6499 closed
Tcp.Segment: TCP retransmission on timer seq = 452897159
Listening on https://mirage.io/
301 REDIRECT https://mirage.io
conn 6714 closed
Tcp.Segment: TCP retransmission on timer seq = 452893210

Dave

On Mon, Jun 29, 2015 at 7:36 PM, Amir Chaudhry <notifications@github.com>
wrote:

> These seem to be the issues Thomas is referring to (just so they're
> linked):
>
>    - mirage/mirage-tcpip#140
>    <https://github.com/mirage/mirage-tcpip/issues/140>
>    - mirage/mirage-tcpip#157
>    <https://github.com/mirage/mirage-tcpip/issues/157>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-www/issues/351#issuecomment-116790663>.
>



-- 
Dave Scott

**Comment by MagnusS** [comment] 2015-06-29 20:17
Regarding https://github.com/mirage/mirage-tcpip/issues/157, it seems that if we loose a packet we are sometimes unable to recover and the connection stalls - and in some cases this also triggers lots of retransmissions and duplicate ACKs. I'm not sure what happens to those connections afterwards... or how common it is. But it is relatively easy to reproduce by running the iperf w/packet loss test a few times (at least on my machine)

**Comment by avsm** [comment] 2015-06-30 08:18
It's probably easiest to modify the TCP/IP stack to dump a pcap trace for any connection above a certain latency.

**Comment by yomimono** [comment] 2015-07-01 08:58
Does this seem better for folks since #355 was merged?

**Comment by avsm** [comment] 2015-07-01 09:00
massively better from my tests

**Comment by amirmc** [comment] 2015-07-01 09:49
**Hugely** improved from my subjective usage of the site. :)

Best wishes,
Amir

--
Sent via mobile

**Comment by samoht** [comment] 2015-07-01 09:51
I'm happy to have a fast website again

**Closed** 2015-07-01 09:50 UTC
