### ISSUE TITLE
warnings in dream/paf dependancy cause `dune build` to fail

### ISSUE THREAD

**Issue by RyanGibb** [mirage/mirage-www#765] opened 2022-09-21 13:09 UTC
```
$ dune build mirage/
File "mirage/duniverse/dream/src/vendor/paf/lib/paf.ml", line 345, characters 16-17:
345 |         | Error e ->  Logs.info (fun m -> m "Error: unknown"); Lwt.return ()));
                      ^
Error (warning 27 [unused-var-strict]): unused variable e.
```
Using `profile --release` fixes this:
```
$ dune build mirage/ --profile release
```

**Comment by samoht** [comment] 2024-04-12 07:46
Closing as I can't reproduce

**Closed by samoht** 2024-04-12 07:46 UTC
