### ISSUE TITLE
pindepends of dream to git repo doesn't clone submodules

### ISSUE THREAD

**Issue by RyanGibb** [mirage/mirage-www#763] opened 2022-09-21 12:41 UTC
dream is pinned with
```
 ["dream.dev" "git+https://github.com/TheLortex/dream.git#650b216d0f8b6f322110b80f03eaa5183b88a8d4"] # branch master+mirage
```
The tarballs from opam contain submodules in dream/src/vendor. Pinning this to a git repo doesn't seem to do a recursive clone, resulting in the error:
```
make
opam exec -- dune build --root . @install
File "mirage/duniverse/dream/src/vendor/dune", line 9, characters 11-14:
9 |   (modules paf)
               ^^^
Error: Module Paf doesn't exist.
File "mirage/duniverse/dream/src/vendor/dune", line 16, characters 11-15:
16 |   (modules alpn)
                ^^^^
Error: Module Alpn doesn't exist.
File "mirage/duniverse/dream/src/vendor/dune", line 23, characters 11-21:
23 |   (modules paf_mirage)
                ^^^^^^^^^^
Error: Module Paf_mirage doesn't exist.
File "mirage/duniverse/dream/src/vendor/dune", line 31, characters 11-13:
31 |   (modules lE)
                ^^
Error: Module LE doesn't exist.
make: *** [Makefile.user:5: all] Error 1
```
This can be fixed with
```
$ mirage/duniverse/
$ rm -rf dream
$ git clone --recurse-submodules https://github.com/TheLortex/dream.git
$ git checkout 650b216d0f8b6f322110b80f03eaa5183b88a8d4
```

**Comment by RyanGibb** [comment] 2022-09-21 12:44
This was fixed with https://github.com/RyanGibb/opam-nix/commit/64859a2881e565a71fd93c5c14f77e4329f57a4b for building with nix

**Comment by samoht** [comment] 2024-04-12 07:48
Closing as I can't reproduce - something has changed in opam-monorepo` that fixed it since then

**Closed by samoht** 2024-04-12 07:48 UTC
