### ISSUE TITLE
High latency (~1 min): known issue?

### ISSUE THREAD

**Issue by jmitchell** [mirage/mirage-www#488] opened 2016-09-02 06:31 UTC
On multiple occasions pages at https://mirago.io took as long as 30 to 90 seconds to load. According to a trace in Wireshark there were 143/518 (27.6%) packets dropped while loading one page.

Are there known issues in Mirage or this application that would explain it? Are there server-side analytics that could help? I realize there are a lot of potential explanations, and many are outside Mirage's control. For what it's worth I'm using a reliable broadband connection in Seattle. I rarely see this behavior with other websites.

**Comment by avsm** [comment] 2016-09-02 08:28
The variability of the latency is often less than a minute, but i have observed this too. I have not got a packet trace though ...

**Comment by mato** [comment] 2016-09-02 08:48
@jmitchell Could you upload a copy of the problematic packet trace somewhere?

**Comment by jmitchell** [comment] 2016-09-02 17:53
Here's a screenshot of [this page](https://mirage.io/wiki/weekly-2016-07-27) loaded in Chrome with the network traffic and timing logged. I intentionally disabled the cache.

![mirage-nocache](https://cloud.githubusercontent.com/assets/77286/18212557/b78baeb2-70f8-11e6-8767-44b9ad8d5ed0.png)

I have the corresponding pcap, but would prefer not making it public unless/until I work out how to scrub it more. Alternatively, I could email it to a trusted Mirage dev or two who want to investigate.

By the way, these problems are frequent for me. Are either of you able to frequently replicate this? It's easier to tell after you clear/disable your browser cache. Occasionally pages fully load within 2-3 seconds, but very often it takes at least a minute. This is measured by when Chrome's Network tab shows "DOMContentLoaded" with elapsed time in blue. Note that "Finish: _ ms/s/min" in the status bar of the Network tab does _not_ mean it's finished; it's updated as assets are downloaded.

**Comment by jmitchell** [comment] 2016-09-02 18:11
You can find the CSV export of the pcap [here](https://gist.github.com/jmitchell/e16564363e8ca48fc80224d9d11f5eed). Notice there are a lot of TCP retransmissions.

**Comment by yomimono** [comment] 2016-09-04 14:19
Thanks for the detailed report! We've done a lot of work on tcpip that is currently on trunk but not yet released, which means that https://mirage.io is not running it. I'll check whether this behavior persists with the latest tcpip checkout today.

**Comment by jmitchell** [comment] 2016-09-04 16:48
Thanks for investigating @yomimono.

**Comment by avsm** [comment] 2016-09-09 13:25
mirage/mirage-tcpip#239 will definitely help with this due to being on the recovery path, but still need to find source of packet loss

**Comment by yomimono** [comment] 2016-09-15 15:51
https://mirage.io has been rebuilt with `tcpip` version 2.8.1, which includes #239 .  I wasn't able to reproduce with the new version -- @jmitchell , can you let us know one way or the other?

**Comment by jmitchell** [comment] 2016-09-15 16:28
Load times are significantly better now, but may need more attention. Most pages are loading within 5 seconds without local browser caching. The [blog](https://mirage.io/blog/) is an outlier in my ad-hoc sample, frequently taking ~10 seconds to load sans cache.

Do you have a sense for the server's bottleneck now? Are response-time logs available?

**Comment by yomimono** [comment] 2017-05-18 14:03
We've been leaving this issue open as a proxy for "better performance testing for `mirage-tcpip`", but I've just opened a real issue for that over at https://github.com/mirage/mirage-tcpip/issues/314 .  As such, I'm closing this issue.  Please do continue to report performance problems as you see them; this was extremely helpful and we're grateful for your contribution, @jmitchell !

**Closed by yomimono** 2017-05-18 14:03 UTC
